#!/bin/bash

homedir="$( cd "$( dirname "$0" )" && pwd )"
cd ${homedir} && source devel/setup.sh

SPEED=25
MOTOR_ID=1

for (( i=1; i<=$#; i++));
do
  val=$((i+1))
  case "${!i}" in
      "--id")
          val=$((i+1))
          MOTOR_ID=${!val}
          ;;
      "--speed")
  	      SPEED=${!val}
  	      ;;
      "--help") echo " [--id]: ID (as an integer number) of the motor to control the speed. By default it is 1. "
          echo " "
          echo " [--speed]:  (Optional) Sets the speed of the motor. If not provided, by default motor runs with 25m/s. int and float is possible."
          exit
          ;;
  esac
done

cmd="rosservice call /conveyor_belt_agent_$MOTOR_ID/setMotorSpeedSimMid $'isEnabled: true\nspeed: $SPEED'"
eval $cmd

echo "$SPEED m/s is commanded to the motor-$MOTOR_ID"
