// Generated by gencpp from file dobot/ContMotorControl.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_CONTMOTORCONTROL_H
#define DOBOT_MESSAGE_CONTMOTORCONTROL_H

#include <ros/service_traits.h>


#include <dobot/ContMotorControlRequest.h>
#include <dobot/ContMotorControlResponse.h>


namespace dobot
{

struct ContMotorControl
{

typedef ContMotorControlRequest Request;
typedef ContMotorControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ContMotorControl
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::ContMotorControl > {
  static const char* value()
  {
    return "83e4a796d51a754bc20fc8ddae5d173f";
  }

  static const char* value(const ::dobot::ContMotorControl&) { return value(); }
};

template<>
struct DataType< ::dobot::ContMotorControl > {
  static const char* value()
  {
    return "dobot/ContMotorControl";
  }

  static const char* value(const ::dobot::ContMotorControl&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::ContMotorControlRequest> should match 
// service_traits::MD5Sum< ::dobot::ContMotorControl > 
template<>
struct MD5Sum< ::dobot::ContMotorControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::ContMotorControl >::value();
  }
  static const char* value(const ::dobot::ContMotorControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::ContMotorControlRequest> should match 
// service_traits::DataType< ::dobot::ContMotorControl > 
template<>
struct DataType< ::dobot::ContMotorControlRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::ContMotorControl >::value();
  }
  static const char* value(const ::dobot::ContMotorControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::ContMotorControlResponse> should match 
// service_traits::MD5Sum< ::dobot::ContMotorControl > 
template<>
struct MD5Sum< ::dobot::ContMotorControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::ContMotorControl >::value();
  }
  static const char* value(const ::dobot::ContMotorControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::ContMotorControlResponse> should match 
// service_traits::DataType< ::dobot::ContMotorControl > 
template<>
struct DataType< ::dobot::ContMotorControlResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::ContMotorControl >::value();
  }
  static const char* value(const ::dobot::ContMotorControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_CONTMOTORCONTROL_H
