// Generated by gencpp from file dobot/GenerateAbnormalTorque.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_GENERATEABNORMALTORQUE_H
#define DOBOT_MESSAGE_GENERATEABNORMALTORQUE_H

#include <ros/service_traits.h>


#include <dobot/GenerateAbnormalTorqueRequest.h>
#include <dobot/GenerateAbnormalTorqueResponse.h>


namespace dobot
{

struct GenerateAbnormalTorque
{

typedef GenerateAbnormalTorqueRequest Request;
typedef GenerateAbnormalTorqueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GenerateAbnormalTorque
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::GenerateAbnormalTorque > {
  static const char* value()
  {
    return "44f381e1746ec656377c4e7f22e5a647";
  }

  static const char* value(const ::dobot::GenerateAbnormalTorque&) { return value(); }
};

template<>
struct DataType< ::dobot::GenerateAbnormalTorque > {
  static const char* value()
  {
    return "dobot/GenerateAbnormalTorque";
  }

  static const char* value(const ::dobot::GenerateAbnormalTorque&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::GenerateAbnormalTorqueRequest> should match 
// service_traits::MD5Sum< ::dobot::GenerateAbnormalTorque > 
template<>
struct MD5Sum< ::dobot::GenerateAbnormalTorqueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::GenerateAbnormalTorque >::value();
  }
  static const char* value(const ::dobot::GenerateAbnormalTorqueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::GenerateAbnormalTorqueRequest> should match 
// service_traits::DataType< ::dobot::GenerateAbnormalTorque > 
template<>
struct DataType< ::dobot::GenerateAbnormalTorqueRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::GenerateAbnormalTorque >::value();
  }
  static const char* value(const ::dobot::GenerateAbnormalTorqueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::GenerateAbnormalTorqueResponse> should match 
// service_traits::MD5Sum< ::dobot::GenerateAbnormalTorque > 
template<>
struct MD5Sum< ::dobot::GenerateAbnormalTorqueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::GenerateAbnormalTorque >::value();
  }
  static const char* value(const ::dobot::GenerateAbnormalTorqueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::GenerateAbnormalTorqueResponse> should match 
// service_traits::DataType< ::dobot::GenerateAbnormalTorque > 
template<>
struct DataType< ::dobot::GenerateAbnormalTorqueResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::GenerateAbnormalTorque >::value();
  }
  static const char* value(const ::dobot::GenerateAbnormalTorqueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_GENERATEABNORMALTORQUE_H
