// Generated by gencpp from file dobot/GetColorSensorResponse.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_GETCOLORSENSORRESPONSE_H
#define DOBOT_MESSAGE_GETCOLORSENSORRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot
{
template <class ContainerAllocator>
struct GetColorSensorResponse_
{
  typedef GetColorSensorResponse_<ContainerAllocator> Type;

  GetColorSensorResponse_()
    : result(0)
    , value_r(0)
    , value_g(0)
    , value_b(0)  {
    }
  GetColorSensorResponse_(const ContainerAllocator& _alloc)
    : result(0)
    , value_r(0)
    , value_g(0)
    , value_b(0)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;

   typedef uint8_t _value_r_type;
  _value_r_type value_r;

   typedef uint8_t _value_g_type;
  _value_g_type value_g;

   typedef uint8_t _value_b_type;
  _value_b_type value_b;





  typedef boost::shared_ptr< ::dobot::GetColorSensorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot::GetColorSensorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetColorSensorResponse_

typedef ::dobot::GetColorSensorResponse_<std::allocator<void> > GetColorSensorResponse;

typedef boost::shared_ptr< ::dobot::GetColorSensorResponse > GetColorSensorResponsePtr;
typedef boost::shared_ptr< ::dobot::GetColorSensorResponse const> GetColorSensorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot::GetColorSensorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot::GetColorSensorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dobot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'dobot': ['/home/cangorur/Workspace/chariot/conveyor_simulation_guthub/src/dobot/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dobot::GetColorSensorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot::GetColorSensorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::GetColorSensorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::GetColorSensorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::GetColorSensorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::GetColorSensorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot::GetColorSensorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8245cb6d39e4a443eba0ed44524e8d92";
  }

  static const char* value(const ::dobot::GetColorSensorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8245cb6d39e4a443ULL;
  static const uint64_t static_value2 = 0xeba0ed44524e8d92ULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot::GetColorSensorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot/GetColorSensorResponse";
  }

  static const char* value(const ::dobot::GetColorSensorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot::GetColorSensorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int32 result\n\
\n\
uint8 value_r\n\
\n\
uint8 value_g\n\
\n\
uint8 value_b\n\
\n\
";
  }

  static const char* value(const ::dobot::GetColorSensorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot::GetColorSensorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.value_r);
      stream.next(m.value_g);
      stream.next(m.value_b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetColorSensorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot::GetColorSensorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot::GetColorSensorResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
    s << indent << "value_r: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value_r);
    s << indent << "value_g: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value_g);
    s << indent << "value_b: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value_b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_MESSAGE_GETCOLORSENSORRESPONSE_H
