// Generated by gencpp from file dobot/InitConveyorBeltAgent.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_INITCONVEYORBELTAGENT_H
#define DOBOT_MESSAGE_INITCONVEYORBELTAGENT_H

#include <ros/service_traits.h>


#include <dobot/InitConveyorBeltAgentRequest.h>
#include <dobot/InitConveyorBeltAgentResponse.h>


namespace dobot
{

struct InitConveyorBeltAgent
{

typedef InitConveyorBeltAgentRequest Request;
typedef InitConveyorBeltAgentResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InitConveyorBeltAgent
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::InitConveyorBeltAgent > {
  static const char* value()
  {
    return "3c2bcf2ff0894cb3058b1bf4c8c4175a";
  }

  static const char* value(const ::dobot::InitConveyorBeltAgent&) { return value(); }
};

template<>
struct DataType< ::dobot::InitConveyorBeltAgent > {
  static const char* value()
  {
    return "dobot/InitConveyorBeltAgent";
  }

  static const char* value(const ::dobot::InitConveyorBeltAgent&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::InitConveyorBeltAgentRequest> should match 
// service_traits::MD5Sum< ::dobot::InitConveyorBeltAgent > 
template<>
struct MD5Sum< ::dobot::InitConveyorBeltAgentRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::InitConveyorBeltAgent >::value();
  }
  static const char* value(const ::dobot::InitConveyorBeltAgentRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::InitConveyorBeltAgentRequest> should match 
// service_traits::DataType< ::dobot::InitConveyorBeltAgent > 
template<>
struct DataType< ::dobot::InitConveyorBeltAgentRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::InitConveyorBeltAgent >::value();
  }
  static const char* value(const ::dobot::InitConveyorBeltAgentRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::InitConveyorBeltAgentResponse> should match 
// service_traits::MD5Sum< ::dobot::InitConveyorBeltAgent > 
template<>
struct MD5Sum< ::dobot::InitConveyorBeltAgentResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::InitConveyorBeltAgent >::value();
  }
  static const char* value(const ::dobot::InitConveyorBeltAgentResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::InitConveyorBeltAgentResponse> should match 
// service_traits::DataType< ::dobot::InitConveyorBeltAgent > 
template<>
struct DataType< ::dobot::InitConveyorBeltAgentResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::InitConveyorBeltAgent >::value();
  }
  static const char* value(const ::dobot::InitConveyorBeltAgentResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_INITCONVEYORBELTAGENT_H
