// Generated by gencpp from file dobot/InitMotorControlApp.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_INITMOTORCONTROLAPP_H
#define DOBOT_MESSAGE_INITMOTORCONTROLAPP_H

#include <ros/service_traits.h>


#include <dobot/InitMotorControlAppRequest.h>
#include <dobot/InitMotorControlAppResponse.h>


namespace dobot
{

struct InitMotorControlApp
{

typedef InitMotorControlAppRequest Request;
typedef InitMotorControlAppResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InitMotorControlApp
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::InitMotorControlApp > {
  static const char* value()
  {
    return "3c2bcf2ff0894cb3058b1bf4c8c4175a";
  }

  static const char* value(const ::dobot::InitMotorControlApp&) { return value(); }
};

template<>
struct DataType< ::dobot::InitMotorControlApp > {
  static const char* value()
  {
    return "dobot/InitMotorControlApp";
  }

  static const char* value(const ::dobot::InitMotorControlApp&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::InitMotorControlAppRequest> should match 
// service_traits::MD5Sum< ::dobot::InitMotorControlApp > 
template<>
struct MD5Sum< ::dobot::InitMotorControlAppRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::InitMotorControlApp >::value();
  }
  static const char* value(const ::dobot::InitMotorControlAppRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::InitMotorControlAppRequest> should match 
// service_traits::DataType< ::dobot::InitMotorControlApp > 
template<>
struct DataType< ::dobot::InitMotorControlAppRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::InitMotorControlApp >::value();
  }
  static const char* value(const ::dobot::InitMotorControlAppRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::InitMotorControlAppResponse> should match 
// service_traits::MD5Sum< ::dobot::InitMotorControlApp > 
template<>
struct MD5Sum< ::dobot::InitMotorControlAppResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::InitMotorControlApp >::value();
  }
  static const char* value(const ::dobot::InitMotorControlAppResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::InitMotorControlAppResponse> should match 
// service_traits::DataType< ::dobot::InitMotorControlApp > 
template<>
struct DataType< ::dobot::InitMotorControlAppResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::InitMotorControlApp >::value();
  }
  static const char* value(const ::dobot::InitMotorControlAppResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_INITMOTORCONTROLAPP_H
