// Generated by gencpp from file dobot/InitMotorControlAppResponse.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_INITMOTORCONTROLAPPRESPONSE_H
#define DOBOT_MESSAGE_INITMOTORCONTROLAPPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot
{
template <class ContainerAllocator>
struct InitMotorControlAppResponse_
{
  typedef InitMotorControlAppResponse_<ContainerAllocator> Type;

  InitMotorControlAppResponse_()
    : success(0)  {
    }
  InitMotorControlAppResponse_(const ContainerAllocator& _alloc)
    : success(0)  {
  (void)_alloc;
    }



   typedef int32_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::dobot::InitMotorControlAppResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot::InitMotorControlAppResponse_<ContainerAllocator> const> ConstPtr;

}; // struct InitMotorControlAppResponse_

typedef ::dobot::InitMotorControlAppResponse_<std::allocator<void> > InitMotorControlAppResponse;

typedef boost::shared_ptr< ::dobot::InitMotorControlAppResponse > InitMotorControlAppResponsePtr;
typedef boost::shared_ptr< ::dobot::InitMotorControlAppResponse const> InitMotorControlAppResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot::InitMotorControlAppResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot::InitMotorControlAppResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dobot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'dobot': ['/home/cangorur/Workspace/chariot/conveyor_simulation_guthub/src/dobot/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dobot::InitMotorControlAppResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot::InitMotorControlAppResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::InitMotorControlAppResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::InitMotorControlAppResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::InitMotorControlAppResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::InitMotorControlAppResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot::InitMotorControlAppResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c2bcf2ff0894cb3058b1bf4c8c4175a";
  }

  static const char* value(const ::dobot::InitMotorControlAppResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c2bcf2ff0894cb3ULL;
  static const uint64_t static_value2 = 0x058b1bf4c8c4175aULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot::InitMotorControlAppResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot/InitMotorControlAppResponse";
  }

  static const char* value(const ::dobot::InitMotorControlAppResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot::InitMotorControlAppResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 success\n\
\n\
";
  }

  static const char* value(const ::dobot::InitMotorControlAppResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot::InitMotorControlAppResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InitMotorControlAppResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot::InitMotorControlAppResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot::InitMotorControlAppResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<int32_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_MESSAGE_INITMOTORCONTROLAPPRESPONSE_H
