// Generated by gencpp from file dobot/OneTimeMotorControl.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_ONETIMEMOTORCONTROL_H
#define DOBOT_MESSAGE_ONETIMEMOTORCONTROL_H

#include <ros/service_traits.h>


#include <dobot/OneTimeMotorControlRequest.h>
#include <dobot/OneTimeMotorControlResponse.h>


namespace dobot
{

struct OneTimeMotorControl
{

typedef OneTimeMotorControlRequest Request;
typedef OneTimeMotorControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OneTimeMotorControl
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::OneTimeMotorControl > {
  static const char* value()
  {
    return "5ea0a2786a30f3b5a13cda84a619c75a";
  }

  static const char* value(const ::dobot::OneTimeMotorControl&) { return value(); }
};

template<>
struct DataType< ::dobot::OneTimeMotorControl > {
  static const char* value()
  {
    return "dobot/OneTimeMotorControl";
  }

  static const char* value(const ::dobot::OneTimeMotorControl&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::OneTimeMotorControlRequest> should match 
// service_traits::MD5Sum< ::dobot::OneTimeMotorControl > 
template<>
struct MD5Sum< ::dobot::OneTimeMotorControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::OneTimeMotorControl >::value();
  }
  static const char* value(const ::dobot::OneTimeMotorControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::OneTimeMotorControlRequest> should match 
// service_traits::DataType< ::dobot::OneTimeMotorControl > 
template<>
struct DataType< ::dobot::OneTimeMotorControlRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::OneTimeMotorControl >::value();
  }
  static const char* value(const ::dobot::OneTimeMotorControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::OneTimeMotorControlResponse> should match 
// service_traits::MD5Sum< ::dobot::OneTimeMotorControl > 
template<>
struct MD5Sum< ::dobot::OneTimeMotorControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::OneTimeMotorControl >::value();
  }
  static const char* value(const ::dobot::OneTimeMotorControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::OneTimeMotorControlResponse> should match 
// service_traits::DataType< ::dobot::OneTimeMotorControl > 
template<>
struct DataType< ::dobot::OneTimeMotorControlResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::OneTimeMotorControl >::value();
  }
  static const char* value(const ::dobot::OneTimeMotorControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_ONETIMEMOTORCONTROL_H
