// Generated by gencpp from file dobot/pid_control_data.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_PID_CONTROL_DATA_H
#define DOBOT_MESSAGE_PID_CONTROL_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot
{
template <class ContainerAllocator>
struct pid_control_data_
{
  typedef pid_control_data_<ContainerAllocator> Type;

  pid_control_data_()
    : power_real(0.0)
    , power_calc(0.0)
    , speed_min(0.0)
    , speed_max(0.0)  {
    }
  pid_control_data_(const ContainerAllocator& _alloc)
    : power_real(0.0)
    , power_calc(0.0)
    , speed_min(0.0)
    , speed_max(0.0)  {
  (void)_alloc;
    }



   typedef float _power_real_type;
  _power_real_type power_real;

   typedef float _power_calc_type;
  _power_calc_type power_calc;

   typedef float _speed_min_type;
  _speed_min_type speed_min;

   typedef float _speed_max_type;
  _speed_max_type speed_max;





  typedef boost::shared_ptr< ::dobot::pid_control_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot::pid_control_data_<ContainerAllocator> const> ConstPtr;

}; // struct pid_control_data_

typedef ::dobot::pid_control_data_<std::allocator<void> > pid_control_data;

typedef boost::shared_ptr< ::dobot::pid_control_data > pid_control_dataPtr;
typedef boost::shared_ptr< ::dobot::pid_control_data const> pid_control_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot::pid_control_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot::pid_control_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dobot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'dobot': ['/home/cangorur/Workspace/chariot/conveyor_simulation_guthub/src/dobot/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dobot::pid_control_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot::pid_control_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::pid_control_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::pid_control_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::pid_control_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::pid_control_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot::pid_control_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4cad1da3b889b346f0b6364044c5116b";
  }

  static const char* value(const ::dobot::pid_control_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4cad1da3b889b346ULL;
  static const uint64_t static_value2 = 0xf0b6364044c5116bULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot::pid_control_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot/pid_control_data";
  }

  static const char* value(const ::dobot::pid_control_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot::pid_control_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 power_real\n\
float32 power_calc\n\
float32 speed_min\n\
float32 speed_max\n\
";
  }

  static const char* value(const ::dobot::pid_control_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot::pid_control_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.power_real);
      stream.next(m.power_calc);
      stream.next(m.speed_min);
      stream.next(m.speed_max);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pid_control_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot::pid_control_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot::pid_control_data_<ContainerAllocator>& v)
  {
    s << indent << "power_real: ";
    Printer<float>::stream(s, indent + "  ", v.power_real);
    s << indent << "power_calc: ";
    Printer<float>::stream(s, indent + "  ", v.power_calc);
    s << indent << "speed_min: ";
    Printer<float>::stream(s, indent + "  ", v.speed_min);
    s << indent << "speed_max: ";
    Printer<float>::stream(s, indent + "  ", v.speed_max);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_MESSAGE_PID_CONTROL_DATA_H
