// Generated by gencpp from file dobot/ReadRegRequest.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_READREGREQUEST_H
#define DOBOT_MESSAGE_READREGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot
{
template <class ContainerAllocator>
struct ReadRegRequest_
{
  typedef ReadRegRequest_<ContainerAllocator> Type;

  ReadRegRequest_()
    : id(0)
    , reg_address(0)
    , data_length(0)  {
    }
  ReadRegRequest_(const ContainerAllocator& _alloc)
    : id(0)
    , reg_address(0)
    , data_length(0)  {
  (void)_alloc;
    }



   typedef int16_t _id_type;
  _id_type id;

   typedef int16_t _reg_address_type;
  _reg_address_type reg_address;

   typedef int16_t _data_length_type;
  _data_length_type data_length;





  typedef boost::shared_ptr< ::dobot::ReadRegRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot::ReadRegRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ReadRegRequest_

typedef ::dobot::ReadRegRequest_<std::allocator<void> > ReadRegRequest;

typedef boost::shared_ptr< ::dobot::ReadRegRequest > ReadRegRequestPtr;
typedef boost::shared_ptr< ::dobot::ReadRegRequest const> ReadRegRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot::ReadRegRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot::ReadRegRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dobot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'dobot': ['/home/cangorur/Workspace/chariot/conveyor_simulation_guthub/src/dobot/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dobot::ReadRegRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot::ReadRegRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::ReadRegRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::ReadRegRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::ReadRegRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::ReadRegRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot::ReadRegRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e0bc8ece5d942f70f5b4bbdc91f6175d";
  }

  static const char* value(const ::dobot::ReadRegRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe0bc8ece5d942f70ULL;
  static const uint64_t static_value2 = 0xf5b4bbdc91f6175dULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot::ReadRegRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot/ReadRegRequest";
  }

  static const char* value(const ::dobot::ReadRegRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot::ReadRegRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 id\n\
int16 reg_address\n\
int16 data_length\n\
";
  }

  static const char* value(const ::dobot::ReadRegRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot::ReadRegRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.reg_address);
      stream.next(m.data_length);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReadRegRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot::ReadRegRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot::ReadRegRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.id);
    s << indent << "reg_address: ";
    Printer<int16_t>::stream(s, indent + "  ", v.reg_address);
    s << indent << "data_length: ";
    Printer<int16_t>::stream(s, indent + "  ", v.data_length);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_MESSAGE_READREGREQUEST_H
