// Generated by gencpp from file dobot/ReadRegResponse.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_READREGRESPONSE_H
#define DOBOT_MESSAGE_READREGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot
{
template <class ContainerAllocator>
struct ReadRegResponse_
{
  typedef ReadRegResponse_<ContainerAllocator> Type;

  ReadRegResponse_()
    : payload()  {
    }
  ReadRegResponse_(const ContainerAllocator& _alloc)
    : payload(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _payload_type;
  _payload_type payload;





  typedef boost::shared_ptr< ::dobot::ReadRegResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot::ReadRegResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ReadRegResponse_

typedef ::dobot::ReadRegResponse_<std::allocator<void> > ReadRegResponse;

typedef boost::shared_ptr< ::dobot::ReadRegResponse > ReadRegResponsePtr;
typedef boost::shared_ptr< ::dobot::ReadRegResponse const> ReadRegResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot::ReadRegResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot::ReadRegResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dobot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'dobot': ['/home/cangorur/Workspace/chariot/conveyor_simulation_guthub/src/dobot/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dobot::ReadRegResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot::ReadRegResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::ReadRegResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::ReadRegResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::ReadRegResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::ReadRegResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot::ReadRegResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e23f13f94a8370e611d697cb5cac5588";
  }

  static const char* value(const ::dobot::ReadRegResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe23f13f94a8370e6ULL;
  static const uint64_t static_value2 = 0x11d697cb5cac5588ULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot::ReadRegResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot/ReadRegResponse";
  }

  static const char* value(const ::dobot::ReadRegResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot::ReadRegResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16[] payload\n\
\n\
";
  }

  static const char* value(const ::dobot::ReadRegResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot::ReadRegResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.payload);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReadRegResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot::ReadRegResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot::ReadRegResponse_<ContainerAllocator>& v)
  {
    s << indent << "payload[]" << std::endl;
    for (size_t i = 0; i < v.payload.size(); ++i)
    {
      s << indent << "  payload[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.payload[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_MESSAGE_READREGRESPONSE_H
