// Generated by gencpp from file dobot/SetDynamixelSpeed.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_SETDYNAMIXELSPEED_H
#define DOBOT_MESSAGE_SETDYNAMIXELSPEED_H

#include <ros/service_traits.h>


#include <dobot/SetDynamixelSpeedRequest.h>
#include <dobot/SetDynamixelSpeedResponse.h>


namespace dobot
{

struct SetDynamixelSpeed
{

typedef SetDynamixelSpeedRequest Request;
typedef SetDynamixelSpeedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetDynamixelSpeed
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::SetDynamixelSpeed > {
  static const char* value()
  {
    return "33258add9094c00c2480650dfbe4cddc";
  }

  static const char* value(const ::dobot::SetDynamixelSpeed&) { return value(); }
};

template<>
struct DataType< ::dobot::SetDynamixelSpeed > {
  static const char* value()
  {
    return "dobot/SetDynamixelSpeed";
  }

  static const char* value(const ::dobot::SetDynamixelSpeed&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::SetDynamixelSpeedRequest> should match 
// service_traits::MD5Sum< ::dobot::SetDynamixelSpeed > 
template<>
struct MD5Sum< ::dobot::SetDynamixelSpeedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetDynamixelSpeed >::value();
  }
  static const char* value(const ::dobot::SetDynamixelSpeedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetDynamixelSpeedRequest> should match 
// service_traits::DataType< ::dobot::SetDynamixelSpeed > 
template<>
struct DataType< ::dobot::SetDynamixelSpeedRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::SetDynamixelSpeed >::value();
  }
  static const char* value(const ::dobot::SetDynamixelSpeedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::SetDynamixelSpeedResponse> should match 
// service_traits::MD5Sum< ::dobot::SetDynamixelSpeed > 
template<>
struct MD5Sum< ::dobot::SetDynamixelSpeedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetDynamixelSpeed >::value();
  }
  static const char* value(const ::dobot::SetDynamixelSpeedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetDynamixelSpeedResponse> should match 
// service_traits::DataType< ::dobot::SetDynamixelSpeed > 
template<>
struct DataType< ::dobot::SetDynamixelSpeedResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::SetDynamixelSpeed >::value();
  }
  static const char* value(const ::dobot::SetDynamixelSpeedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_SETDYNAMIXELSPEED_H
