// Generated by gencpp from file dobot/SetDynamixelSpeedRequest.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_SETDYNAMIXELSPEEDREQUEST_H
#define DOBOT_MESSAGE_SETDYNAMIXELSPEEDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot
{
template <class ContainerAllocator>
struct SetDynamixelSpeedRequest_
{
  typedef SetDynamixelSpeedRequest_<ContainerAllocator> Type;

  SetDynamixelSpeedRequest_()
    : isEnabled(false)
    , speed(0.0)  {
    }
  SetDynamixelSpeedRequest_(const ContainerAllocator& _alloc)
    : isEnabled(false)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _isEnabled_type;
  _isEnabled_type isEnabled;

   typedef double _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::dobot::SetDynamixelSpeedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot::SetDynamixelSpeedRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetDynamixelSpeedRequest_

typedef ::dobot::SetDynamixelSpeedRequest_<std::allocator<void> > SetDynamixelSpeedRequest;

typedef boost::shared_ptr< ::dobot::SetDynamixelSpeedRequest > SetDynamixelSpeedRequestPtr;
typedef boost::shared_ptr< ::dobot::SetDynamixelSpeedRequest const> SetDynamixelSpeedRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot::SetDynamixelSpeedRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot::SetDynamixelSpeedRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dobot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'dobot': ['/home/cangorur/Workspace/chariot/conveyor_simulation_guthub/src/dobot/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dobot::SetDynamixelSpeedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot::SetDynamixelSpeedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::SetDynamixelSpeedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::SetDynamixelSpeedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::SetDynamixelSpeedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::SetDynamixelSpeedRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot::SetDynamixelSpeedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "35dd5d1dbccecc83a105549701815d3f";
  }

  static const char* value(const ::dobot::SetDynamixelSpeedRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x35dd5d1dbccecc83ULL;
  static const uint64_t static_value2 = 0xa105549701815d3fULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot::SetDynamixelSpeedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot/SetDynamixelSpeedRequest";
  }

  static const char* value(const ::dobot::SetDynamixelSpeedRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot::SetDynamixelSpeedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool isEnabled\n\
float64 speed\n\
";
  }

  static const char* value(const ::dobot::SetDynamixelSpeedRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot::SetDynamixelSpeedRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isEnabled);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetDynamixelSpeedRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot::SetDynamixelSpeedRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot::SetDynamixelSpeedRequest_<ContainerAllocator>& v)
  {
    s << indent << "isEnabled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isEnabled);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_MESSAGE_SETDYNAMIXELSPEEDREQUEST_H
