// Generated by gencpp from file dobot/WriteRegRequest.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_WRITEREGREQUEST_H
#define DOBOT_MESSAGE_WRITEREGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot
{
template <class ContainerAllocator>
struct WriteRegRequest_
{
  typedef WriteRegRequest_<ContainerAllocator> Type;

  WriteRegRequest_()
    : id(0)
    , reg_address(0)
    , data()  {
    }
  WriteRegRequest_(const ContainerAllocator& _alloc)
    : id(0)
    , reg_address(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef int16_t _id_type;
  _id_type id;

   typedef int16_t _reg_address_type;
  _reg_address_type reg_address;

   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::dobot::WriteRegRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot::WriteRegRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WriteRegRequest_

typedef ::dobot::WriteRegRequest_<std::allocator<void> > WriteRegRequest;

typedef boost::shared_ptr< ::dobot::WriteRegRequest > WriteRegRequestPtr;
typedef boost::shared_ptr< ::dobot::WriteRegRequest const> WriteRegRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot::WriteRegRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot::WriteRegRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dobot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'dobot': ['/home/cangorur/Workspace/chariot/conveyor_simulation_guthub/src/dobot/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dobot::WriteRegRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot::WriteRegRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::WriteRegRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::WriteRegRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::WriteRegRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::WriteRegRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot::WriteRegRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4caf60cf8e773bbe0706999dfae0d07e";
  }

  static const char* value(const ::dobot::WriteRegRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4caf60cf8e773bbeULL;
  static const uint64_t static_value2 = 0x0706999dfae0d07eULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot::WriteRegRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot/WriteRegRequest";
  }

  static const char* value(const ::dobot::WriteRegRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot::WriteRegRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 id\n\
int16 reg_address\n\
int16[] data\n\
";
  }

  static const char* value(const ::dobot::WriteRegRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot::WriteRegRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.reg_address);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WriteRegRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot::WriteRegRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot::WriteRegRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.id);
    s << indent << "reg_address: ";
    Printer<int16_t>::stream(s, indent + "  ", v.reg_address);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_MESSAGE_WRITEREGREQUEST_H
